export const courses = [
  "Peach Circuit",
  "Shy Guy Beach",
  "Riverside Park",
  "Bowser Castle 1",
  "Mario Circuit",
  "Boo Lake",
  "Cheese Land",
  "Bowser Castle 2",
  "Luigi Circuit",
  "Sky Garden",
  "Cheep Cheep Island",
  "Sunset Wilds",
  "Snow Land",
  "Ribbon Road",
  "Yoshi Desert",
  "Bowser Castle 3",
  "Lakeside Park",
  "Broken Pier",
  "Bowser Castle 4",
  "Rainbow Road",
  "Retro Mario Circuit 1",
  "Retro Donut Plains 1",
  "Retro Ghost Valley 1",
  "Retro Bowser Castle 1",
  "Retro Mario Circuit 2",
  "Retro Choco Island 1",
  "Retro Ghost Valley 2",
  "Retro Donut Plains 2",
  "Retro Bowser Castle 2",
  "Retro Mario Circuit 3",
  "Retro Koopa Beach 1",
  "Retro Choco Island 2",
  "Retro Vanilla Lake 1",
  "Retro Bowser Castle 3",
  "Retro Mario Circuit 4",
  "Retro Donut Plains 3",
  "Retro Koopa Beach 2",
  "Retro Ghost Valley 3",
  "Retro Vanilla Lake 2",
  "Retro Rainbow Road",
];
