# databases:
#   - name: mkscvids
#     plan: free

# services:
#   - type: web
#     name: mkscvids-web
#     env: node
#     plan: free
#     # buildCommand: "npm install -g pnpm@8.15.7 && pnpm install && pnpm run build"
#     # startCommand: "npx prisma migrate deploy && pnpm run start"
#     buildCommand: npm i && npm run build && npm prune --production
#     startCommand: npx prisma migrate deploy && npm run start
#     healthCheckPath: /healthcheck
#     envVars:
#       - key: DATABASE_URL
#         fromDatabase:
#           name: mkscvids
#           property: connectionString
#       - key: SESSION_SECRET
#         generateValue: true
#       - key: NODE_ENV #required so NODE_ENV is set in build env
#         value: production
